name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Create .env.production from GitHub Secrets
      working-directory: frontend
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env.production
        echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env.production

    - name: Build the Vite project
      working-directory: frontend
      run: npm run build -- --mode production

    - name: Debug directory structure
      run: |
        ls -la
        ls -la frontend
        ls -la frontend/dist

    - name: Sync build folder to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "frontend/dist"
        DEST_DIR: ""

    - name: Configure S3 website settings
    run: |
      aws s3api put-bucket-website --bucket ${{ secrets.S3_BUCKET_NAME }} --website-configuration '{"IndexDocument":{"Suffix":"index.html"},"ErrorDocument":{"Key":"index.html"}}'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}