name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH into EC2 and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Connect via SSH and pull latest code
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd Beta
          git pull origin main
          source backend/venv/bin/activate
          sudo systemctl restart netxplore
