name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH into EC2 and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Connect via SSH and pull latest code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Beta
            git pull origin main
            source backend/venv/bin/activate

            mkdir -p backend/uploads
            chmod 755 backend/uploads

            sudo sed -i '/client_max_body_size/d' /etc/nginx/sites-available/default
            sudo sed -i '/server_name.*;/a \    client_max_body_size 100M;' /etc/nginx/sites-available/default

            sudo nginx -t && sudo systemctl reload nginx

            sudo systemctl restart netxplore
